project:
  type: website
  render: 
    - "*.qmd"
    - "!Municipais/*"
    
website:
  title: "Indicadores Censo SUAS"
#  navbar:
#    left:
#      - href: index.qmd
#        text: Brasil
#      - href: municipais.qmd
#        text: Municipais
  sidebar:
#    - title: "Municipais"
      contents:
        - href: index.qmd
          text: Apresentação
        - href: nacional.qmd
          text: Brasil
        - auto: Municipais

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  echo: false
  message: false
  warning: false
  cache: false
  freeze: auto

lang: pt   
number-sections: true
fig-cap-location: top

crossref:
  fig-title: Gráfico     # (default is "Figure")
  tbl-title: Tabela     # (default is "Table")
  title-delim: "."      # (default is ":")
  fig-prefix: Gráfico   # (default is "Figure")
  tbl-prefix: Tabela    # (default is "Table")
#  ref-hyperlink: false # (default is true)
