project:
  type: website
  render: 
    - "*.qmd"
    - "!Municipais/Relatório*"
    
website:
  title: "Indicadores Censo SUAS"
  navbar:
    left:
      - text: "Início"
        href: index.qmd

  sidebar:
    - id: municipais
      contents:
        - auto: Municipais

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    template-partials:
      - title-block.html

execute:
  echo: false
  message: false
  warning: false
  cache: false
  freeze: false

lang: pt   
fig-cap-location: top

