project:
  type: website
  render: 
    - "*.qmd"
    - "!Municipais/*"
    
website:
  title: "Indicadores Censo SUAS"
#  navbar:
#    left:
#      - href: index.qmd
#        text: Brasil
#      - href: municipais.qmd
#        text: Municipais
  sidebar:
#    - title: "Municipais"
      contents:
        - href: index.qmd
          text: Apresentação
        - href: nacional.qmd
          text: Brasil
        - auto: Municipais

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    template-partials:
      - title-block.html

execute:
  echo: false
  message: false
  warning: false
  cache: false
  freeze: auto

lang: pt   
fig-cap-location: top

