{
  "hash": "8b3c248a21b1c1875b7fffe3e88a9526",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Prado\nauthor: \"SAGICAD e SNAS / MDS\"\n\nnumber-sections: true\n\nfig-cap-location: top\n\ncrossref:\n  fig-title: Gráfico     # (default is \"Figure\")\n  tbl-title: Tabela     # (default is \"Table\")\n  title-delim: \".\"      # (default is \":\")\n  fig-prefix: Gráfico   # (default is \"Figure\")\n  tbl-prefix: Tabela    # (default is \"Table\")\n#  ref-hyperlink: false # (default is true)\n\n#format:\n#  html:\n#    embed-resources: true\n\nparams:\n  municipio: 292550\n# municipio: 355030 # São Paulo\n# municipio: 316660 # Menor Município\n# municipio: 330455 # Rio de Janeiro\n# municipio: 110028 # CRAS EF nível 1\n# municipio: 110005 # CRAS EF nível 3, Serviços nível 1\n# municipio: 110007 # CRAS EF nível 4\n# municipio: 110012 # CRAS Serviços nível 1 município Grande\n# municipio: 521925 # Sem nota de Conselho em 2023\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n---\nsubtitle: \"Relatório de Indicadores Censo SUAS 2023 do município de Prado, Bahia\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n# ID CRAS: Índice de Desenvolvimento do CRAS\n\nO ID CRAS é um indicador sintético que retrata o grau de desenvolvimento do CRAS. Ele é composto por três dimensões: Estrutura Física, Recursos Humanos e Serviços & Benefícios. Em cada dimensão é atribuída uma nota de 1 a 5 de acordo com critérios indicativos do nível de desenvolvimento do CRAS, sendo 5 o nível máximo de desenvolvimento. O ID CRAS é a média das notas alcançadas nas três dimensões.\n\nO @fig-ID-CRAS mostra a evolução das médias do ID CRAS ao longo dos anos no município de Prado, Bahia.\n\n\n::: {.cell fig.footer='Fonte: MDS, Censo SUAS.'}\n::: {.cell-output-display}\n![Evolução das médias do ID CRAS, 2014 a 2023: Prado, Bahia](Relatório-Indicadores-2023---Bahia-Prado_files/figure-html/fig-ID-CRAS-1.png){#fig-ID-CRAS width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell fig.footer='Fonte: MDS, Censo SUAS.'}\n::: {.cell-output-display}\n![Quantidade de CRAS em cada nível de ID, 2023: Prado, Bahia](Relatório-Indicadores-2023---Bahia-Prado_files/figure-html/fig-ID-CRAS-nivel-1.png){#fig-ID-CRAS-nivel width=672}\n:::\n:::\n\n\n\n::: {#tbl-cras-por-capacidade .cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Quantidade de CRAS em 2023 no município de Prado por capacidade de referenciamento.\n\n|Capacidade de até:           | Quantidade|\n|:----------------------------|----------:|\n|2.500 famílias referenciadas |          0|\n|3.500 famílias referenciadas |          2|\n|5.000 famílias referenciadas |          0|\n\n\n:::\n:::\n\n\nAs seções a seguir apresentam os resultados do município de Prado em cada uma das dimensões do ID CRAS, bem como os requisitos para se alcançar os níveis superiores.\n\n\n::: {.cell}\n\n## ID CRAS: Dimensão Estrutura Física\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n### CRAS com capacidade de referenciamento para até 2.500 ou 3.500 famílias\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\nNa dimensão Estrutura Física, o nível de ID dos CRAS com capacidade de referenciamento para até 2.500 ou 3.500 famílias no município de Prado varia de 1 a 3.\n\nO CRAS de **nível 1**, com capacidade de referenciamento para até 2.500 ou 3.500 famílias, na dimensão Estrutura Física:\n\n\n::: {.cell}\n\n* Possui **menos de 2 salas de atendimento**; ou\n* **Não possui banheiro**; ou\n* Funciona em **prédio compartilhado com ONG, ou com compartilhamento de todas as salas de atendimento**.\n:::\n\n\nPara alcançar o **nível 2** na dimensão Estrutura Física, o CRAS com capacidade de referenciamento para até 2.500 ou 3.500 famílias precisa:\n\n\n::: {.cell}\n\n* Possuir no mínimo **2 salas de atendimento**; e\n* Possuir pelo menos **1 banheiro**.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nPara alcançar o **nível 3** na dimensão Estrutura Física, o CRAS com capacidade de referenciamento para até 2.500 ou 3.500 famílias precisa, além dos requisitos do nível 2:\n\n\n::: {.cell}\n\n* Possuir **recepção**; e\n* Possuir **acessibilidade, ao menos parcial**.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nPara alcançar o **nível 4** na dimensão Estrutura Física, o CRAS com capacidade de referenciamento para até 2.500 ou 3.500 famílias precisa, além dos resquisitos do nível 3:\n\n\n::: {.cell}\n\n* Possuir **pelo menos 1 das salas de atendimento com capacidade para 15 ou mais pessoas**; e\n* Possuir no mínimo **2 banheiros**; e\n* Possuir **pelo menos 1 computador conectado à internet**.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n### CRAS com capacidade de referenciamento para até 5.000 famílias\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nPrado não tem CRAS com capacidade de referenciamento para até 5.000 famílias.\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n## ID CRAS: Dimensão Recursos Humanos\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n### CRAS com capacidade de referenciamento para até 2.500 famílias\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nPrado não tem CRAS com capacidade de referenciamento para até 2.500 famílias.\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n### CRAS com capacidade de referenciamento para até 3.500 famílias\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\nNa dimensão Recursos Humanos, o nível de ID dos CRAS com capacidade de referenciamento para até 3.500 famílias no município de Prado varia de 2 a 5.\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nO CRAS de **nível 2**, com capacidade de referenciamento para até 3.500 famílias, na dimensão Recursos Humanos:\n\n\n::: {.cell}\n\n* Possui no mínimo **5** profissionais, sendo, pelo menos **2** com nível superior*; e\n* Possui pelo menos **1 Assistente Social ou 1 Psicólogo**.  \n:::\n\n\nPara alcançar o **nível 3** na dimensão Recursos Humanos, o CRAS com capacidade de referenciamento para até 3.500 famílias precisa, além dos requisitos do nível 2:\n\n\n::: {.cell}\n\n* Possuir no mínimo **6** (8, se EV) profissionais, sendo pelo menos **3** (4, se EV) com nível superior; e\n* Possuir no mínimo **2 Assistentes Sociais** (3, se EV).\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nPara alcançar o **nível 4** na dimensão Recursos Humanos, o CRAS com capacidade de referenciamento para até 3.500 famílias precisa, além dos resquisitos do nível 3:\n\n\n::: {.cell}\n\n* Possuir no mínimo **6** (9, se EV) profissionais, sendo pelo menos **4** (6, se EV) com nível superior; e\n* Possuir **coordenador** com nível superior.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nPara alcançar o **nível 5** na dimensão Recursos Humanos, o CRAS com capacidade de referenciamento para até 3.500 famílias precisa, além dos requisitos do nível 4:\n\n\n::: {.cell}\n\n* Possuir no mínimo **7** (11, se EV) **profissionais** (sendo pelo menos **4** (6, se EV) com **nível superior**); e\n* Possuir no mínimo **1 Psicólogo**; e \n* Possuir no mínimo **1** profissional de nível superior com **vínculo estatutário ou empregado público celetista**.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n### CRAS com capacidade de referenciamento para até 5.000 famílias\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nPrado não tem CRAS com capacidade de referenciamento para até 5.000 famílias.\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n## ID CRAS: Dimensão Serviços & Benefícios\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\nNa dimensão Serviços & Benefícios, o nível de ID dos CRAS no município de Prado varia de 1 a 2.\n\nO CRAS de **nível 1** na dimensão Serviços & Benefícios em município de porte Pequeno II:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n* **Não realiza** alguma(s) das seguintes atividades essenciais do PAIF: **acompanhamento de famílias, e/ou grupo/oficina com famílias, e/ou visitas domiciliares, e/ou orientação**; ou\n* Possui **articulação frágil ou inexistente** com os Serviços de Educação, com os Serviços de Saúde e com os CREAS; ou \n* Não possui profissionais de Serviço Social nem de Psicologia.\n:::\n\n\nPara alcançar o **nível 2** na dimensão Serviços & Benefícios, o CRAS em município de porte Pequeno II precisa:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n* **Executar o PAIF**, realizando no mínimo as seguintes atividades: **acompanhamento de famílias, grupo/oficina com famílias e visitas domiciliares**; e \n* Possuir **forte articulação com pelo menos um dos seguintes Serviços: Serviços de Educação, Serviços de Saúde e CREAS**.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nPara alcançar o **nível 3** na dimensão Serviços & Benefícios, o CRAS em município de porte Pequeno II precisa, além dos requisitos do nível 2:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n* **Executar o PAIF** realizando **orientação/acompanhamento para inserção no BPC**, além das atividades exigidas para o nível 2; e\n* Possuir oferta de Serviço de Convivência **pelo menos para um ciclo de vida** (oferta direta do CRAS ou por meio de unidades a ele referenciadas); e\n* Possuir **forte articulação com o(s) CREAS e com os Serviços de Educação e Saúde** no território.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n# ID CREAS: Índice de Desenvolvimento do CREAS\n\nO ID CREAS é um indicador sintético que retrata o grau de desenvolvimento do CREAS. Ele é composto por três dimensões: Estrutura Física, Recursos Humanos e Serviços & Benefícios. Em cada dimensão é atribuída uma nota de 1 a 5 de acordo com critérios indicativos do nível de desenvolvimento do CREAS, sendo 5 o nível máximo de desenvolvimento. O ID CREAS é a média das notas alcançadas nas três dimensões.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nO @fig-ID-CREAS mostra a evolução das médias do ID CREAS ao longo dos anos no município de Prado, Bahia.\n\n\n::: {.cell fig.footer='Fonte: MDS, Censo SUAS.'}\n::: {.cell-output-display}\n![Evolução das médias do ID CREAS, 2014 a 2023: Prado, Bahia](Relatório-Indicadores-2023---Bahia-Prado_files/figure-html/fig-ID-CREAS-1.png){#fig-ID-CREAS width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell fig.footer='Fonte: MDS, Censo SUAS.'}\n\n:::\n\n\nAs seções a seguir apresentam os resultados do município de Prado em cada uma das dimensões do ID CREAS, bem como os requisitos para se alcançar os níveis superiores.\n\n\n::: {.cell}\n\n## ID CREAS: Dimensão Estrutura Física\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Estrutura Física, o nível de ID do CREAS no município de Prado é 4.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nO CREAS de **nível 4** na dimensão Estrutura Física em município de porte Pequeno II:\n\n\n::: {.cell}\n\n* Possui recepção; e\n* Possui no mínimo 2 banheiros; e\n* Possui 1 ou mais computadores com Internet; e\n* Possui veículo próprio ou compartilhado; e\n* Possui acessibilidade, ao menos parcial; e\n* Possui 3 salas ou mais para atendimento (5 se CREAS Regional).\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nPara alcançar o **nível 5** na dimensão Estrutura Física, o CREAS em município de porte Pequeno II precisa, além dos requisitos do nível 4:\n\n\n::: {.cell}\n\n* Possuir 1 ou mais sala Administrativa; e\n* Possuir kit equipamento: Telefone, Impressora, 2 ou mais computadores com Internet, além de Veículo próprio ou compartilhado; e\n* Possuir acessibilidade (com ou sem ABNT); e\n* Possuir pelo menos 1 das salas para atendimento com capacidade para 15 ou mais pessoas.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n## ID CREAS: Dimensão Recursos Humanos\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Recursos Humanos, o nível de ID do CREAS no município de Prado é 4.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nO CREAS de **nível 4** na dimensão Recursos Humanos em município de porte Pequeno II:\n\n\n::: {.cell}\n\n* Possui no mínimo 1 Advogado; e\n* Possui Coordenador com nível superior; e\n* Tem quantidade total de trabalhadores (nível superior e médio) maior ou igual a 5 (10, se CREAS Regional), sendo no mínimo 4 (6, se CREAS Regional) deles de nível superior; e\n* Possui no mínimo 1 Assistente Social e 1 Psicólogo (além disso, se for CREAS Regional, o total de Assistentes Sociais mais Psicólogos deve ser maior ou igual a 4).\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nPara alcançar o **nível 5** na dimensão Recursos Humanos, o CREAS em município de porte Pequeno II precisa, além dos requisitos do nível 4:\n\n\n::: {.cell}\n\n* Ter quantidade total de trabalhadores (nível superior e médio) maior ou igual a 7 (14, se CREAS Regional, sendo neste caso no mínimo 7 de nível superior); e\n* Se for CREAS Regional, possuir no mínimo 2 Assistentes Sociais; e\n* Se for CREAS Regional, possuir no mínimo 2 Psicólogos; e\n* Possuir no mínimo 1 (2, se CREAS Regional) trabalhador de nível superior com vínculo estatutário ou empregado público celetista.\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n## ID CREAS: Dimensão Serviços & Benefícios\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Serviços & Benefícios, o nível de ID do CREAS no município de Prado é 3.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nO CREAS de **nível 3** na dimensão Serviços & Benefícios em município de porte Pequeno II:\n\n\n::: {.cell}\n\n* Oferta o PAEFI assegurando a realização, pelo menos, das seguintes atividades: Entrevistas de acolhida para avaliação inicial dos casos, Atendimento psicossocial individual/familiar, Construção de Plano Individual e/ou Familiar de atendimento, Visitas domiciliares e Elaboração de relatórios técnicos sobre casos em acompanhamento; e\n* Possui forte articulação com o CRAS e com o Conselho Tutelar; e\n* Oferta atendimento para variadas situações de violência ou violação de direitos e para os diferentes ciclos de vida; e\n* Oferta o Serviço de MSE (APLICA-SE SOMENTE SE O MUNICÍPIO RECEBER COFINANCIAMENTO ou se for CREAS Regional).\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nPara alcançar o **nível 4** na dimensão Serviços & Benefícios, o CREAS em município de porte Pequeno II precisa, além dos requisitos do nível 3:\n\n\n::: {.cell}\n\n* Ofertar o PAEFI assegurando a realização da atividade de Atendimento psicossocial em grupo (além da realização das atividades exigidas no nível 3); e\n* Ter quantidade média de casos em acompanhamento no mês, dividida pela equipe técnica (AS + PSI) menor ou igual a 50 casos; e\n* Ofertar o Serviço de MSE assegurando a elaboração do Plano Individual de Atendimento (PIA) do adolescente (APLICA-SE SOMENTE SE O MUNICÍPIO RECEBER COFINANCIAMENTO ou se for CREAS Regional); e\n* Ofertar o Serviço de Abordagem ou ter o Serviço referenciado (APLICA-SE SOMENTE SE O MUNICÍPIO RECEBER COFINANCIAMENTO ou se for CREAS Regional).\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n# ID Conselho: Índice de Desenvolvimento dos Conselhos de Assistência Social\n\nO ID Conselho é um indicador sintético de desenvolvimento com o objetivo de avaliar o controle social no SUAS. Ele é composto por três dimensões: Estrutura Administrativa, Dinâmica de Funcionamento e Composição do Conselho. Em cada dimensão é atribuída uma nota de 1 a 5 de acordo com critérios indicativos do nível de desenvolvimento do Conselho, sendo 5 o nível máximo de desenvolvimento. O ID Conselho é a média das notas alcançadas nas três dimensões.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nO @fig-ID-conselho mostra a evolução das médias do ID Conselho ao longo dos anos no município de Prado, Bahia.\n\n\n::: {.cell fig.footer='Fonte: MDS, Censo SUAS.'}\n::: {.cell-output-display}\n![Evolução das médias do ID Conselho, 2014 a 2023: Prado, Bahia](Relatório-Indicadores-2023---Bahia-Prado_files/figure-html/fig-ID-conselho-1.png){#fig-ID-conselho width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nAs seções a seguir apresentam os resultados do município de Prado em cada uma das dimensões do ID Conselho, bem como os requisitos para se alcançar os níveis superiores.\n\n\n::: {.cell}\n\n## ID Conselho: Dimensão Estrutura Administrativa\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Estrutura Administrativa, o nível de ID do Conselho no município de Prado é 1.\n\n\n\n\n\nO Conselho de **nível 1** na dimensão Estrutura Administrativa em município de porte Pequeno II:\n\n\n::: {.cell}\n\n* **Não** possui previsão de recursos na Lei Orçamentária Anual e **não** utiliza para as despesas de seu funcionamento o mínimo de 3% do IGD; ou \n* **Não** possui sala (exclusiva ou compartilhada); ou \n* **Não** possui Secretaria Executiva.\n:::\n\n\nPara alcançar o **nível 2** na dimensão Estrutura Administrativa, o Conselho em município de porte Pequeno II precisa:\n\n\n::: {.cell}\n\n* Possuir previsão de recursos na Lei Orçamentária Anual ou utilizar para as despesas de seu funcionamento o mínimo de 3% do IGD; e\n* Possuir uma ou mais salas de uso exclusivo ou compartilhado; e\n* Possuir Secretaria Executiva. \n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n## ID Conselho: Dimensão Dinâmica de Funcionamento\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Dinâmica de Funcionamento, o nível de ID do Conselho no município de Prado é 3.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nO Conselho de **nível 3** na dimensão Dinâmica de Funcionamento em município de porte Pequeno II:\n\n\n::: {.cell}\n\n* Realizou 6 ou mais reuniões plenárias no ano anterior (ordinárias e extraordinárias); e\n* Possui Regimento Interno; e\n* Deliberou sobre o Plano de Assistência Social; e\n* Acompanha o cumprimento de deliberações da Conferência Municipal.\n:::\n\n\nPara alcançar o **nível 4** na dimensão Dinâmica de Funcionamento, o Conselho em município de porte Pequeno II precisa, além dos requisitos do nível 3:\n\n\n::: {.cell}\n\n* Realizar 8 ou mais reuniões plenárias no ano anterior (ordinárias e extraordinárias); e\n* Deliberar sobre o orçamento do executivo; e\n* Ser instância de Controle Social do Bolsa Família.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n## ID Conselho: Dimensão Composição do Conselho\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Composição do Conselho, o nível de ID do Conselho no município de Prado é 3.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nO Conselho de **nível 3** na dimensão Composição do Conselho em município de porte Pequeno II:\n\n\n::: {.cell}\n\n* Possui no mínimo 6 conselheiros titulares; e\n* Possui pelo menos um conselheiro titular representante de usuários ou organização de usuários; e\n* Possui pelo menos um conselheiro titular representante de trabalhadores do setor; e\n* Possui alternância na presidência entre os representantes de governo e os representantes da sociedade civil. \n:::\n\n\nPara alcançar o **nível 4** na dimensão Composição do Conselho, o Conselho em município de porte Pequeno II precisa, além dos requisitos do nível 3:\n\n\n::: {.cell}\n\n* Possuir representantes da sociedade civil eleitos por assembleias constituídas para esse fim; e\n* Possuir Presidente e Vice-Presidente eleitos em plenária; e\n* Que o Conselheiro possa ser reconduzido uma única vez. \n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n",
    "supporting": [
      "Relatório-Indicadores-2023---Bahia-Prado_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}