{
  "hash": "47199d95f8d1c6bc7b11d0ba41fd7d7c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Cachoeiro de Itapemirim\nauthor: \"SAGICAD e SNAS / MDS\"\n\nnumber-sections: true\n\nfig-cap-location: top\n\ncrossref:\n  fig-title: Gráfico     # (default is \"Figure\")\n  tbl-title: Tabela     # (default is \"Table\")\n  title-delim: \".\"      # (default is \":\")\n  fig-prefix: Gráfico   # (default is \"Figure\")\n  tbl-prefix: Tabela    # (default is \"Table\")\n#  ref-hyperlink: false # (default is true)\n\n#format:\n#  html:\n#    embed-resources: true\n\nparams:\n  municipio: 320120\n# municipio: 355030 # São Paulo\n# municipio: 316660 # Menor Município\n# municipio: 330455 # Rio de Janeiro\n# municipio: 110028 # CRAS EF nível 1\n# municipio: 110005 # CRAS EF nível 3, Serviços nível 1\n# municipio: 110007 # CRAS EF nível 4\n# municipio: 110012 # CRAS Serviços nível 1 município Grande\n# municipio: 521925 # Sem nota de Conselho em 2023\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n---\nsubtitle: \"Relatório de Indicadores Censo SUAS 2023 do município de Cachoeiro de Itapemirim, Espírito Santo\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n# ID CRAS: Índice de Desenvolvimento do CRAS\n\nO ID CRAS é um indicador sintético que retrata o grau de desenvolvimento do CRAS. Ele é composto por três dimensões: Estrutura Física, Recursos Humanos e Serviços & Benefícios. Em cada dimensão é atribuída uma nota de 1 a 5 de acordo com critérios indicativos do nível de desenvolvimento do CRAS, sendo 5 o nível máximo de desenvolvimento. O ID CRAS é a média das notas alcançadas nas três dimensões.\n\nO @fig-ID-CRAS mostra a evolução das médias do ID CRAS ao longo dos anos no município de Cachoeiro de Itapemirim, Espírito Santo.\n\n\n::: {.cell fig.footer='Fonte: MDS, Censo SUAS.'}\n::: {.cell-output-display}\n![Evolução das médias do ID CRAS, 2014 a 2023: Cachoeiro de Itapemirim, Espírito Santo](Relatório-Indicadores-2023---Espírito-Santo-Cachoeiro-de-Itapemirim_files/figure-html/fig-ID-CRAS-1.png){#fig-ID-CRAS width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell fig.footer='Fonte: MDS, Censo SUAS.'}\n::: {.cell-output-display}\n![Quantidade de CRAS em cada nível de ID, 2023: Cachoeiro de Itapemirim, Espírito Santo](Relatório-Indicadores-2023---Espírito-Santo-Cachoeiro-de-Itapemirim_files/figure-html/fig-ID-CRAS-nivel-1.png){#fig-ID-CRAS-nivel width=672}\n:::\n:::\n\n\n\n::: {#tbl-cras-por-capacidade .cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Quantidade de CRAS em 2023 no município de Cachoeiro de Itapemirim por capacidade de referenciamento.\n\n|Capacidade de até:           | Quantidade|\n|:----------------------------|----------:|\n|2.500 famílias referenciadas |          1|\n|3.500 famílias referenciadas |          1|\n|5.000 famílias referenciadas |          6|\n\n\n:::\n:::\n\n\nAs seções a seguir apresentam os resultados do município de Cachoeiro de Itapemirim em cada uma das dimensões do ID CRAS, bem como os requisitos para se alcançar os níveis superiores.\n\n\n::: {.cell}\n\n## ID CRAS: Dimensão Estrutura Física\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n### CRAS com capacidade de referenciamento para até 2.500 ou 3.500 famílias\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\nNa dimensão Estrutura Física, o nível de ID dos CRAS com capacidade de referenciamento para até 2.500 ou 3.500 famílias no município de Cachoeiro de Itapemirim varia de 3 a 4.\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nO CRAS de **nível 3**, com capacidade de referenciamento para até 2.500 ou 3.500 famílias, na dimensão Estrutura Física:\n\n\n::: {.cell}\n\n* Possui **recepção**; e\n* Possui no mínimo **2 salas de atendimento**; e\n* Possui pelo menos **1 banheiro**; e\n* Possui **acessibilidade, ao menos parcial**.\n:::\n\n\nPara alcançar o **nível 4** na dimensão Estrutura Física, o CRAS com capacidade de referenciamento para até 2.500 ou 3.500 famílias precisa, além dos resquisitos do nível 3:\n\n\n::: {.cell}\n\n* Possuir **pelo menos 1 das salas de atendimento com capacidade para 15 ou mais pessoas**; e\n* Possuir no mínimo **2 banheiros**; e\n* Possuir **pelo menos 1 computador conectado à internet**.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nPara alcançar o **nível 5** na dimensão Estrutura Física, o CRAS com capacidade de referenciamento para até 2.500 ou 3.500 famílias precisa, além dos requisitos do nível 4:\n\n\n::: {.cell}\n\n* Possuir no mínimo **1 sala administrativa**; e\n* Possuir **acessibilidade**; e\n* Possuir conjunto de equipamentos que inclua, no mínimo: **2 computadores conectados à internet, impressora, telefone e veículo exclusivo ou compartilhado**.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n### CRAS com capacidade de referenciamento para até 5.000 famílias\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\nNa dimensão Estrutura Física, o nível de ID dos CRAS com capacidade de referenciamento para até 5.000 famílias no município de Cachoeiro de Itapemirim varia de 4 a 5.\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nO CRAS de **nível 4**, com capacidade de referenciamento para até 5.000 famílias, na dimensão Estrutura Física:\n\n\n::: {.cell}\n\n* Possui **recepção**; e\n* Possui no mínimo **4 salas de atendimento**, sendo **pelo menos 1 com capacidade para 15 ou mais pessoas**; e\n* Possui no mínimo **2 banheiros**; e\n* Possui **acessibilidade, ao menos parcial**; e\n* Possui **pelo menos 2 computadores conectados à internet**.\n:::\n\n\nPara alcançar o **nível 5** na dimensão Estrutura Física, o CRAS com capacidade de referenciamento para até 5.000 famílias precisa, além dos requisitos do nível 4:\n\n\n::: {.cell}\n\n* Possuir no mínimo **1 sala administrativa**; e\n* Possuir **acessibilidade**; e\n* Possuir conjunto de equipamentos que inclua, no mínimo: **3 computadores conectados à internet, impressora, telefone e veículo exclusivo ou compartilhado**.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n## ID CRAS: Dimensão Recursos Humanos\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n### CRAS com capacidade de referenciamento para até 2.500 famílias\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Recursos Humanos, o nível de ID do CRAS com capacidade de referenciamento para até 2.500 famílias no município de Cachoeiro de Itapemirim é 4.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nO CRAS de **nível 4**, com capacidade de referenciamento para até 2.500 famílias, na dimensão Recursos Humanos:\n\n\n::: {.cell}\n\n* Possui no mínimo **4** (7, se EV) profissionais, sendo pelo menos **3** (5, se EV) com nível superior; e\n* Possui no mínimo **1 Assistente Social** (2, se EV); e \n* Possui **coordenador** com nível superior.\n:::\n\n\nPara alcançar o **nível 5** na dimensão Recursos Humanos, o CRAS com capacidade de referenciamento para até 2.500 famílias precisa, além dos requisitos do nível 4:\n\n\n::: {.cell}\n\n* Possuir no mínimo **5** (9, se EV) **profissionais** (sendo pelo menos **3** (5, se EV) com **nível superior**); e \n* Possuir no mínimo **1 Psicólogo**; e \n* Possuir no mínimo **1** profissional de nível superior com **vínculo estatutário ou empregado público celetista**.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n### CRAS com capacidade de referenciamento para até 3.500 famílias\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Recursos Humanos, o nível de ID do CRAS com capacidade de referenciamento para até 3.500 famílias no município de Cachoeiro de Itapemirim é 2.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nO CRAS de **nível 2**, com capacidade de referenciamento para até 3.500 famílias, na dimensão Recursos Humanos:\n\n\n::: {.cell}\n\n* Possui no mínimo **5** profissionais, sendo, pelo menos **2** com nível superior*; e\n* Possui pelo menos **1 Assistente Social ou 1 Psicólogo**.  \n:::\n\n\nPara alcançar o **nível 3** na dimensão Recursos Humanos, o CRAS com capacidade de referenciamento para até 3.500 famílias precisa, além dos requisitos do nível 2:\n\n\n::: {.cell}\n\n* Possuir no mínimo **6** (8, se EV) profissionais, sendo pelo menos **3** (4, se EV) com nível superior; e\n* Possuir no mínimo **2 Assistentes Sociais** (3, se EV).\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n### CRAS com capacidade de referenciamento para até 5.000 famílias\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nNa dimensão Recursos Humanos, o nível de ID dos CRAS com capacidade de referenciamento para até 5.000 famílias no município de Cachoeiro de Itapemirim é 4.\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nO CRAS de **nível 4**, com capacidade de referenciamento para até 5.000 famílias, na dimensão Recursos Humanos:\n\n\n::: {.cell}\n\n* Possui no mínimo **7** (10, se EV) profissionais, sendo pelo menos **5** (7, se EV) com nível superior; e \n* Possui no mínimo **2 Assistentes Sociais** (3, se EV) e **1 Psicólogo**; e \n* Possui **coordenador** com nível superior.\n:::\n\n\nPara alcançar o **nível 5** na dimensão Recursos Humanos, o CRAS com capacidade de referenciamento para até 5.000 famílias precisa, além dos requisitos do nível 4:\n\n\n::: {.cell}\n\n* Possuir no mínimo **9** (13, se EV) **profissionais** (sendo pelo menos **5** (7, se EV) com **nível superior**); e\n* Possuir no mínimo **2** profissionais de nível superior com **vínculo estatutário ou empregado público celetista**.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n## ID CRAS: Dimensão Serviços & Benefícios\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\nNa dimensão Serviços & Benefícios, o nível de ID dos CRAS no município de Cachoeiro de Itapemirim varia de 2 a 3.\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nO CRAS de **nível 2** na dimensão Serviços & Benefícios em município de porte Grande:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n* **Executa o PAIF**, realizando no mínimo as seguintes atividades: **acompanhamento de famílias, grupo/oficina com famílias e visitas domiciliares**; e \n* Possui **forte articulação com pelo menos um dos seguintes Serviços: Serviços de Educação, Serviços de Saúde e CREAS**.\n:::\n\n\nPara alcançar o **nível 3** na dimensão Serviços & Benefícios, o CRAS em município de porte Grande precisa, além dos requisitos do nível 2:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n* **Executar o PAIF** realizando **orientação/acompanhamento para inserção no BPC**, além das atividades exigidas para o nível 2; e\n* Possuir oferta de Serviço de Convivência **pelo menos para um ciclo de vida** (oferta direta do CRAS ou por meio de unidades a ele referenciadas); e\n* Possuir **forte articulação com o(s) CREAS e com os Serviços de Educação e Saúde** no território.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nPara alcançar o **nível 4** na dimensão Serviços & Benefícios, o CRAS em município de porte Grande precisa, além dos requisitos do nível 3:\n\n\n::: {.cell}\n\n* Ter **quantidade média de famílias em acompanhamento no mês, dividida pela equipe técnica** (Assistentes Sociais e Psicólogos) não inferior a 20 nem superior a 100; e\n* **Executar o PAIF** realizando **palestras, campanhas ou eventos comunitários e acompanhamento dos encaminhamentos realizados**, além das atividades exigidas para o nível 3; e\n* Possuir oferta de Serviço de Convivência **para no mínimo dois ciclos de vida** (oferta direta do CRAS ou por meio de unidades a ele referenciadas); e\n* **Funcionar** no mínimo **5 dias** por semana e **40 horas** semanais.  \n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n# ID CREAS: Índice de Desenvolvimento do CREAS\n\nO ID CREAS é um indicador sintético que retrata o grau de desenvolvimento do CREAS. Ele é composto por três dimensões: Estrutura Física, Recursos Humanos e Serviços & Benefícios. Em cada dimensão é atribuída uma nota de 1 a 5 de acordo com critérios indicativos do nível de desenvolvimento do CREAS, sendo 5 o nível máximo de desenvolvimento. O ID CREAS é a média das notas alcançadas nas três dimensões.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nO @fig-ID-CREAS mostra a evolução das médias do ID CREAS ao longo dos anos no município de Cachoeiro de Itapemirim, Espírito Santo.\n\n\n::: {.cell fig.footer='Fonte: MDS, Censo SUAS.'}\n::: {.cell-output-display}\n![Evolução das médias do ID CREAS, 2014 a 2023: Cachoeiro de Itapemirim, Espírito Santo](Relatório-Indicadores-2023---Espírito-Santo-Cachoeiro-de-Itapemirim_files/figure-html/fig-ID-CREAS-1.png){#fig-ID-CREAS width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell fig.footer='Fonte: MDS, Censo SUAS.'}\n\n:::\n\n\nAs seções a seguir apresentam os resultados do município de Cachoeiro de Itapemirim em cada uma das dimensões do ID CREAS, bem como os requisitos para se alcançar os níveis superiores.\n\n\n::: {.cell}\n\n## ID CREAS: Dimensão Estrutura Física\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Estrutura Física, o nível de ID do CREAS no município de Cachoeiro de Itapemirim é 1.\n\n\n\n\n\nO CREAS de **nível 1** na dimensão Estrutura Física em município de porte Grande:\n\n\n::: {.cell}\n\n* Possui menos de 3 salas; e/ou\n* Não possui banheiro; e/ou\n* Faz compartilhamento dos espaços de atendimento.\n:::\n\n\nPara alcançar o **nível 2** na dimensão Estrutura Física, o CREAS em município de porte Grande precisa:\n\n\n::: {.cell}\n\n* Possuir no mínimo 3 salas (atendimento e/ou administrativa); e\n* Possuir no mínimo 1 banheiro.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n## ID CREAS: Dimensão Recursos Humanos\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Recursos Humanos, o nível de ID do CREAS no município de Cachoeiro de Itapemirim é 3.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nO CREAS de **nível 3** na dimensão Recursos Humanos em município de porte Grande:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n* Possui Coordenador com nível superior; e\n* Tem quantidade total de trabalhadores (nível superior e médio) maior ou igual a 10, sendo no mínimo 5 deles de nível superior; e \n* Tem quantidade total de Assistentes Sociais, mais Psicólogos, maior ou igual a 4, sendo obrigatória a presença de profissionais destas duas áreas.\n:::\n\n\nPara alcançar o **nível 4** na dimensão Recursos Humanos, o CREAS em município de porte Grande precisa, além dos requisitos do nível 3:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n* Possuir no mínimo 1 Advogado; e\n* Ter no mínimo 6 trabalhadores de nível superior.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n## ID CREAS: Dimensão Serviços & Benefícios\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Serviços & Benefícios, o nível de ID do CREAS no município de Cachoeiro de Itapemirim é 3.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nO CREAS de **nível 3** na dimensão Serviços & Benefícios em município de porte Grande:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n* Oferta o PAEFI assegurando a realização, pelo menos, das seguintes atividades: Entrevistas de acolhida para avaliação inicial dos casos, Atendimento psicossocial individual/familiar, Construção de Plano Individual e/ou Familiar de atendimento, Visitas domiciliares e Elaboração de relatórios técnicos sobre casos em acompanhamento; e\n* Possui forte articulação com o CRAS e com o Conselho Tutelar; e\n* Oferta atendimento para variadas situações de violência ou violação de direitos e para os diferentes ciclos de vida; e\n* Oferta o Serviço de MSE.\n:::\n\n\nPara alcançar o **nível 4** na dimensão Serviços & Benefícios, o CREAS em município de porte Grande precisa, além dos requisitos do nível 3:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n* Ofertar o PAEFI assegurando a realização da atividade de Atendimento psicossocial em grupo (além da realização das atividades exigidas no nível 3); e\n* Ter quantidade média de casos em acompanhamento no mês, dividida pela equipe técnica (AS + PSI) menor ou igual a 50 casos; e\n* Ofertar o Serviço de MSE assegurando a elaboração do Plano Individual de Atendimento (PIA) do adolescente; e\n* Ofertar o Serviço de Abordagem ou ter o Serviço referenciado.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n# ID Conselho: Índice de Desenvolvimento dos Conselhos de Assistência Social\n\nO ID Conselho é um indicador sintético de desenvolvimento com o objetivo de avaliar o controle social no SUAS. Ele é composto por três dimensões: Estrutura Administrativa, Dinâmica de Funcionamento e Composição do Conselho. Em cada dimensão é atribuída uma nota de 1 a 5 de acordo com critérios indicativos do nível de desenvolvimento do Conselho, sendo 5 o nível máximo de desenvolvimento. O ID Conselho é a média das notas alcançadas nas três dimensões.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nO @fig-ID-conselho mostra a evolução das médias do ID Conselho ao longo dos anos no município de Cachoeiro de Itapemirim, Espírito Santo.\n\n\n::: {.cell fig.footer='Fonte: MDS, Censo SUAS.'}\n::: {.cell-output-display}\n![Evolução das médias do ID Conselho, 2014 a 2023: Cachoeiro de Itapemirim, Espírito Santo](Relatório-Indicadores-2023---Espírito-Santo-Cachoeiro-de-Itapemirim_files/figure-html/fig-ID-conselho-1.png){#fig-ID-conselho width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nAs seções a seguir apresentam os resultados do município de Cachoeiro de Itapemirim em cada uma das dimensões do ID Conselho, bem como os requisitos para se alcançar os níveis superiores.\n\n\n::: {.cell}\n\n## ID Conselho: Dimensão Estrutura Administrativa\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Estrutura Administrativa, o nível de ID do Conselho no município de Cachoeiro de Itapemirim é 3.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nO Conselho de **nível 3** na dimensão Estrutura Administrativa em município de porte Grande:\n\n\n::: {.cell}\n\n* Possui previsão de recursos na Lei Orçamentária Anual ou utiliza para as despesas de seu funcionamento o mínimo de 3% do IGD; e\n* Possui Secretaria Executiva; e \n* Possui um ou mais computadores conectados à internet; e\n* Possui telefone de uso exclusivo ou compartilhado; e\n* Possui uma ou mais salas de uso exclusivo ou compartilhado.\n:::\n\n\nPara alcançar o **nível 4** na dimensão Estrutura Administrativa, o Conselho em município de porte Grande precisa, além dos requisitos do nível 3:\n\n\n::: {.cell}\n\n* Possuir uma ou mais salas de uso exclusivo.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n## ID Conselho: Dimensão Dinâmica de Funcionamento\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Dinâmica de Funcionamento, o nível de ID do Conselho no município de Cachoeiro de Itapemirim é 5.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\nO Conselho de **nível 5** na dimensão Dinâmica de Funcionamento em município de porte Grande:\n\n\n::: {.cell}\n\n* Realizou 10 ou mais reuniões plenárias no ano anterior (ordinárias e extraordinárias); e\n* Possui Regimento Interno; e\n* Deliberou sobre o orçamento do executivo; e\n* Deliberou sobre o Plano de Assistência Social; e\n* É instância de Controle Social do Bolsa Família; e\n* Acompanha o cumprimento de deliberações da Conferência Municipal; e\n* Fiscaliza os serviços, programas e projetos da rede pública e privada (ou fiscaliza somente a rede pública quando não existe rede privada); e\n* Realiza reuniões/ações de mobilização ou descentralizadas ou ampliadas.\n:::\n\n\n\n::: {.cell}\n\n## ID Conselho: Dimensão Composição do Conselho\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNa dimensão Composição do Conselho, o nível de ID do Conselho no município de Cachoeiro de Itapemirim é 5.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nO Conselho de **nível 5** na dimensão Composição do Conselho em município de porte Grande:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n* Possui no mínimo 10 conselheiros titulares; e\n* Possui representantes da sociedade civil eleitos por assembleias constituídas para esse fim; e\n* Possui pelo menos um conselheiro titular representante de usuários ou organização de usuários; e\n* Possui pelo menos um conselheiro titular representante de trabalhadores do setor; e\n* Possui alternância na presidência entre os representantes de governo e os representantes da sociedade civil; e\n* Possui Presidente e Vice-Presidente eleitos em plenária; e\n* Permite que o Conselheiro possa ser reconduzido uma única vez; e\n* Possui representação governamental da área de assistência, saúde e educação.\n:::\n\n",
    "supporting": [
      "Relatório-Indicadores-2023---Espírito-Santo-Cachoeiro-de-Itapemirim_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}